NAV - Testing Kalman Filter
Hyp-ed/hyped-2024 pull request #68
Opened 2024-02-06 18:19 UTC by misha7b

TODO:
- Work out how to actually run test
- Test that Kalman Filter runs
- Test that Kalman Filter runs correctly by going through calculations on paper

2024-03-04 19:43 UTC, TomLonergan03 requested changes
looks good, a couple of nitpicks

2024-03-04 19:43 UTC, TomLonergan03 commented on lib/navigation/filtering/kalman_filter.cpp
> +                     - kalman_gain * measurement_matrix);
extraneous brackets

2024-03-04 19:43 UTC, TomLonergan03 commented on test/navigation/kalman_filter.cpp
> +#include <random>
what is this used for?

2024-03-04 19:43 UTC, TomLonergan03 commented on test/navigation/kalman_filter.cpp
>  TEST(KalmanFilter, construction)
rename the test

2024-03-04 19:43 UTC, TomLonergan03 commented on test/navigation/kalman_filter.cpp
> +// Expected velocity: 400ms^-1
move these comments above `TEST...`

2024-03-04 19:43 UTC, TomLonergan03 commented on test/navigation/kalman_filter.cpp
> +// Variacnce of measurments:
Variance

2024-03-04 19:43 UTC, TomLonergan03 commented on test/navigation/kalman_filter.cpp
> +// Measurments taken every 1s
Measurements

2024-03-07 18:16 UTC, DylanCavers approved these changes
lgtm

2024-03-07 18:32 UTC, TomLonergan03 requested changes

2024-03-07 18:32 UTC, TomLonergan03 commented on lib/navigation/filtering/kalman_filter.cpp
> +  auto kalman_gain = error_covariance_ * measurement_matrix.transpose()
`const`

2024-03-07 18:32 UTC, TomLonergan03 commented on lib/navigation/filtering/kalman_filter.cpp
> +  auto difference = Eigen::Matrix<core::Float, state_dimension, state_dimension>::Identity()
`const`

2024-03-07 18:32 UTC, TomLonergan03 commented on test/navigation/kalman_filter.cpp
pretty much every variable in here should be `const` unless it has to be mutable

2024-03-08 13:29 UTC, TomLonergan03 requested changes
Real nitpicks but they will also rerun the linter which didn't run on the last push for some reason

2024-03-08 13:29 UTC, TomLonergan03 commented on lib/navigation/filtering/kalman_filter.cpp
> +
remove this whitespace

2024-03-08 13:29 UTC, TomLonergan03 commented on test/navigation/kalman_filter.cpp
> +
and this

2024-03-09 14:54 UTC, TomLonergan03 approved these changes
looks good

2024-03-09 18:27 UTC, merged