SNS - Accelerometer Testing
Hyp-ed/hyped-2024 pull request #98
Opened 2024-04-09 17:41 UTC by licornes-fluos

As we are using the same accelerometer code as last year, here is the code to test it with the current accelerometer.

2024-04-09 17:47 UTC, TomLonergan03 requested changes

2024-04-09 17:47 UTC, TomLonergan03 commented on lib/debug/commands/accelerometer_commands.cpp
> +  const auto accelerometer_read             = "read";
var name `accelerometer_read_name` and set the value `"accelerometer read"`

2024-04-09 17:47 UTC, TomLonergan03 commented on lib/debug/commands/accelerometer_commands.cpp
> +    const auto value_ready  = accelerometer_sensor->isValueReady();  // method already returns state
this should be used, also what does the comment mean?

2024-04-09 17:47 UTC, TomLonergan03 commented on lib/debug/commands/accelerometer_commands.cpp
> +    logger.log(core::LogLevel::kDebug, "Acceleration: %d", *acceleration);
`*acceleration` is a struct, i don't think you can print it like that

2024-04-10 12:34 UTC, licornes-fluos commented on lib/debug/commands/accelerometer_commands.cpp
> +    const auto acceleration = accelerometer_sensor.read();
How to I call this? I tried multiple ways, but it doesn't work. (same for value_ready above)

2024-04-10 13:32 UTC, davidbeechey approved these changes

2024-04-10 13:32 UTC, davidbeechey commented on lib/sensors/accelerometer.hpp
> +  //  const std::uint8_t device_address);
```suggestion
```

2024-05-13 17:53 UTC, davidbeechey approved these changes

2024-07-01 23:41 UTC, TomLonergan03 approved these changes
lets gamble try merge

2024-07-01 23:42 UTC, merged